### ISSUE TITLE
Container Image Not Publicly Published 

### ISSUE THREAD

**Issue by lberk** [cyrusimap/cyrus-docker-test-server#1]
```
% podman pull ghcr.io/cyrusimap/cyrus-docker-test-server:latest
Trying to pull ghcr.io/cyrusimap/cyrus-docker-test-server:latest...
Error: initializing source docker://ghcr.io/cyrusimap/cyrus-docker-test-server:latest: reading manifest latest in ghcr.io/cyrusimap/cyrus-docker-test-server: denied
```

The test server looked perfect for testing an automation I use against a JMAP server.  It'd be great if the image could be published inline with the `README.txt` instructions.

**Comment by rjbs** [comment]
At long last, I made this public: https://github.com/cyrusimap/cyrus-docker-test-server/pkgs/container/cyrus-docker-test-server

Work for you?

I'll get to fresh builds and new work in the new year, I reckon.

**Comment by lberk** [comment]
yes! thank you so much!

**Comment by rjbs** [comment]
No problem, and I'll be interested to hear what you end up doing with it, or getting out of it!
